// Shared sample programs/campaigns for community health
export const samplePrograms = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    title: 'Posyandu Revival: Improving Maternal & Child Health',
    organization: 'Yayasan Sehat Bersama',
    orgLogo: 'https://ui-avatars.com/api/?name=YSB&background=4f46e5&color=fff',
    verified: true,
    urgent: true,
    amount: 18467410,
    target: 25000000,
    daysLeft: 12,
    description: 'Support the revitalization of local Posyandu (integrated health posts) to provide regular check-ups, immunizations, and nutrition counseling for mothers and children in rural areas. Your contribution helps train volunteers, supply vitamins, and ensure every child gets a healthy start.\n\nTogether, we can reduce stunting and improve community health outcomes.',
    storyDate: '23 Agt 2024',
    donors: [
      { name: 'dr. Maya Putri', amount: 50000, time: '5 menit yang lalu' },
      { name: 'Orang Baik', amount: 20000, time: '10 menit yang lalu' },
      { name: 'Louis Steven', amount: 100000, time: '15 menit yang lalu' },
    ],
    prayers: [
      { name: 'Orang Baik', text: 'Semoga anak-anak tumbuh sehat dan kuat!', time: '28 menit yang lalu', count: 12 },
      { name: 'dr. Maya Putri', text: 'Ayo dukung kesehatan ibu dan anak!', time: 'sejam yang lalu', count: 7 },
    ],
    updates: [
      { date: '01 Mei 2025', count: 12 },
    ],
    withdrawals: [
      { date: '01 Mei 2025', count: 5 },
    ],
    donationCount: 46211,
    prayerCount: 6617,
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80',
    title: 'Clean Water for Healthy Communities',
    organization: 'Water4Life Indonesia',
    orgLogo: 'https://ui-avatars.com/api/?name=W4L&background=0ea5e9&color=fff',
    verified: true,
    urgent: false,
    amount: 12000000,
    target: 20000000,
    daysLeft: 20,
    description: 'Help us build and maintain clean water facilities in remote villages. Access to clean water reduces waterborne diseases and improves overall health, especially for children and pregnant women.\n\nYour donation funds water filters, wells, and hygiene education sessions.',
    storyDate: '20 Agt 2024',
    donors: [
      { name: 'Budi Santoso', amount: 75000, time: '2 jam yang lalu' },
      { name: 'Orang Baik', amount: 25000, time: '3 jam yang lalu' },
    ],
    prayers: [
      { name: 'Orang Baik', text: 'Semoga air bersih selalu tersedia.', time: '4 jam yang lalu', count: 3 },
    ],
    updates: [
      { date: '15 Agt 2024', count: 8 },
    ],
    withdrawals: [
      { date: '10 Agt 2024', count: 2 },
    ],
    donationCount: 1200,
    prayerCount: 300,
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&q=80',
    title: 'Mobile Vaccination for Remote Children',
    organization: 'Gerak Vaksin Nusantara',
    orgLogo: 'https://ui-avatars.com/api/?name=GVN&background=22c55e&color=fff',
    verified: true,
    urgent: false,
    amount: 8000000,
    target: 15000000,
    daysLeft: 18,
    description: 'Support our mobile vaccination units to reach children in remote and underserved areas. We provide essential immunizations, health screenings, and health education to prevent outbreaks and save lives.\n\nEvery donation helps us reach more children and communities.',
    storyDate: '18 Agt 2024',
    donors: [
      { name: 'Siti Aminah', amount: 100000, time: '1 jam yang lalu' },
    ],
    prayers: [
      { name: 'Orang Baik', text: 'Semoga anak-anak sehat selalu.', time: '2 jam yang lalu', count: 2 },
    ],
    updates: [
      { date: '10 Agt 2024', count: 5 },
    ],
    withdrawals: [
      { date: '09 Agt 2024', count: 1 },
    ],
    donationCount: 800,
    prayerCount: 120,
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=800&q=80',
    title: 'Mental Health Support for Teens',
    organization: 'Sahabat Remaja Sehat',
    orgLogo: 'https://ui-avatars.com/api/?name=SRS&background=f59e42&color=fff',
    verified: true,
    urgent: false,
    amount: 5000000,
    target: 10000000,
    daysLeft: 25,
    description: 'Help us provide mental health workshops, counseling, and peer support groups for teenagers. Early intervention and support can prevent serious mental health issues and empower youth to thrive.\n\nYour support funds professional counselors, educational materials, and safe spaces for teens.',
    storyDate: '15 Agt 2024',
    donors: [
      { name: 'Rina Dewi', amount: 50000, time: '30 menit yang lalu' },
    ],
    prayers: [
      { name: 'Orang Baik', text: 'Semoga remaja Indonesia sehat jiwa dan raga.', time: '1 jam yang lalu', count: 1 },
    ],
    updates: [
      { date: '12 Agt 2024', count: 3 },
    ],
    withdrawals: [
      { date: '11 Agt 2024', count: 1 },
    ],
    donationCount: 500,
    prayerCount: 50,
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80',
    title: 'Nutrition for School Children',
    organization: 'Gizi Anak Bangsa',
    orgLogo: 'https://ui-avatars.com/api/?name=GAB&background=ef4444&color=fff',
    verified: true,
    urgent: false,
    amount: 9000000,
    target: 20000000,
    daysLeft: 10,
    description: 'Join us in providing nutritious meals and nutrition education to school children in low-income communities. Good nutrition is key to learning and growth.\n\nYour donation provides healthy meals, nutrition workshops, and growth monitoring.',
    storyDate: '10 Agt 2024',
    donors: [
      { name: 'Andi Wijaya', amount: 30000, time: '10 menit yang lalu' },
    ],
    prayers: [
      { name: 'Orang Baik', text: 'Semoga anak-anak tumbuh sehat dan cerdas.', time: '20 menit yang lalu', count: 2 },
    ],
    updates: [
      { date: '08 Agt 2024', count: 2 },
    ],
    withdrawals: [
      { date: '07 Agt 2024', count: 1 },
    ],
    donationCount: 900,
    prayerCount: 80,
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80',
    title: 'Stunting Prevention for Rural Children',
    organization: 'Indonesia Sehat Foundation',
    orgLogo: 'https://ui-avatars.com/api/?name=ISF&background=0ea5e9&color=fff',
    verified: true,
    urgent: true,
    amount: 7000000,
    target: 20000000,
    daysLeft: 15,
    description: 'Help us provide nutrition supplements and education to prevent stunting in rural children. Your support funds growth monitoring, parent workshops, and healthy food packages.',
    storyDate: '12 Agt 2024',
    donors: [ { name: 'Ayu Lestari', amount: 25000, time: '20 menit yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga anak-anak tumbuh sehat.', time: '30 menit yang lalu', count: 2 } ],
    updates: [ { date: '10 Agt 2024', count: 3 } ],
    withdrawals: [ { date: '09 Agt 2024', count: 1 } ],
    donationCount: 300,
    prayerCount: 40,
  },
  {
    id: 7,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    title: 'Mobile Dental Clinic for Kids',
    organization: 'Smile for the Future',
    orgLogo: 'https://ui-avatars.com/api/?name=SFF&background=4f46e5&color=fff',
    verified: true,
    urgent: false,
    amount: 3500000,
    target: 10000000,
    daysLeft: 22,
    description: 'Support our mobile dental clinic to provide free check-ups and dental hygiene education for children in underserved areas.',
    storyDate: '10 Agt 2024',
    donors: [ { name: 'Dewi Anggraini', amount: 50000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga anak-anak selalu sehat giginya.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '08 Agt 2024', count: 2 } ],
    withdrawals: [ { date: '07 Agt 2024', count: 1 } ],
    donationCount: 120,
    prayerCount: 10,
  },
  {
    id: 8,
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&q=80',
    title: 'TB Awareness and Screening',
    organization: 'Lung Health Indonesia',
    orgLogo: 'https://ui-avatars.com/api/?name=LHI&background=22c55e&color=fff',
    verified: true,
    urgent: false,
    amount: 6000000,
    target: 15000000,
    daysLeft: 18,
    description: 'Help us run TB awareness campaigns and free screening in high-risk communities. Early detection saves lives!',
    storyDate: '09 Agt 2024',
    donors: [ { name: 'Bambang S', amount: 30000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga Indonesia bebas TB.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '07 Agt 2024', count: 2 } ],
    withdrawals: [ { date: '06 Agt 2024', count: 1 } ],
    donationCount: 200,
    prayerCount: 20,
  },
  {
    id: 9,
    image: 'https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=800&q=80',
    title: 'Vision Screening for School Children',
    organization: 'Bright Eyes Project',
    orgLogo: 'https://ui-avatars.com/api/?name=BEP&background=ef4444&color=fff',
    verified: true,
    urgent: false,
    amount: 2000000,
    target: 8000000,
    daysLeft: 12,
    description: 'Support free vision screening and glasses for children in need. Good vision is key to learning!',
    storyDate: '08 Agt 2024',
    donors: [ { name: 'Sari P', amount: 20000, time: '30 menit yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga anak-anak bisa belajar dengan baik.', time: '1 jam yang lalu', count: 1 } ],
    updates: [ { date: '06 Agt 2024', count: 1 } ],
    withdrawals: [ { date: '05 Agt 2024', count: 1 } ],
    donationCount: 80,
    prayerCount: 5,
  },
  {
    id: 10,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    title: 'Safe Motherhood Initiative',
    organization: 'Bunda Aman Foundation',
    orgLogo: 'https://ui-avatars.com/api/?name=BAF&background=4f46e5&color=fff',
    verified: true,
    urgent: true,
    amount: 12000000,
    target: 30000000,
    daysLeft: 30,
    description: 'Help us provide safe delivery kits, midwife training, and emergency transport for mothers in remote areas.',
    storyDate: '07 Agt 2024',
    donors: [ { name: 'Linda S', amount: 100000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua ibu dan bayi selamat.', time: '2 jam yang lalu', count: 3 } ],
    updates: [ { date: '05 Agt 2024', count: 2 } ],
    withdrawals: [ { date: '04 Agt 2024', count: 1 } ],
    donationCount: 400,
    prayerCount: 30,
  },
  {
    id: 11,
    image: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=800&q=80',
    title: 'Hearing Aid Access for Children',
    organization: 'Suara Anak Foundation',
    orgLogo: 'https://ui-avatars.com/api/?name=SAF&background=0ea5e9&color=fff',
    verified: true,
    urgent: false,
    amount: 4000000,
    target: 12000000,
    daysLeft: 17,
    description: 'Help provide hearing aids and screenings for children with hearing loss. Early intervention is key to language development.',
    storyDate: '06 Agt 2024',
    donors: [ { name: 'Rudi Hartono', amount: 35000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga anak-anak bisa mendengar dunia.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '05 Agt 2024', count: 1 } ],
    withdrawals: [ { date: '04 Agt 2024', count: 1 } ],
    donationCount: 90,
    prayerCount: 7,
  },
  {
    id: 12,
    image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80',
    title: 'Malaria Prevention Nets',
    organization: 'Sehat Nusantara',
    orgLogo: 'https://ui-avatars.com/api/?name=SN&background=22c55e&color=fff',
    verified: true,
    urgent: true,
    amount: 9000000,
    target: 20000000,
    daysLeft: 14,
    description: 'Distribute mosquito nets and run malaria education in high-risk villages. Protect families from deadly disease.',
    storyDate: '05 Agt 2024',
    donors: [ { name: 'Mira Sari', amount: 50000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua sehat dan terhindar dari malaria.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '04 Agt 2024', count: 2 } ],
    withdrawals: [ { date: '03 Agt 2024', count: 1 } ],
    donationCount: 200,
    prayerCount: 15,
  },
  {
    id: 13,
    image: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=800&q=80',
    title: 'Disability Inclusion Workshops',
    organization: 'Inklusi Indonesia',
    orgLogo: 'https://ui-avatars.com/api/?name=II&background=f59e42&color=fff',
    verified: true,
    urgent: false,
    amount: 2500000,
    target: 10000000,
    daysLeft: 20,
    description: 'Promote disability inclusion and accessibility in schools and communities through workshops and advocacy.',
    storyDate: '04 Agt 2024',
    donors: [ { name: 'Dian P', amount: 20000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua anak mendapat kesempatan yang sama.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '03 Agt 2024', count: 1 } ],
    withdrawals: [ { date: '02 Agt 2024', count: 1 } ],
    donationCount: 60,
    prayerCount: 4,
  },
  {
    id: 14,
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80',
    title: 'Elderly Health Home Visits',
    organization: 'Lansia Bahagia',
    orgLogo: 'https://ui-avatars.com/api/?name=LB&background=ef4444&color=fff',
    verified: true,
    urgent: false,
    amount: 8000000,
    target: 15000000,
    daysLeft: 19,
    description: 'Support home visits for elderly people to monitor health, provide medication, and reduce isolation.',
    storyDate: '03 Agt 2024',
    donors: [ { name: 'Slamet R', amount: 40000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga para lansia sehat dan bahagia.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '02 Agt 2024', count: 1 } ],
    withdrawals: [ { date: '01 Agt 2024', count: 1 } ],
    donationCount: 100,
    prayerCount: 8,
  },
  {
    id: 15,
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80',
    title: 'Dengue Fever Awareness',
    organization: 'Cegah DBD',
    orgLogo: 'https://ui-avatars.com/api/?name=CD&background=0ea5e9&color=fff',
    verified: true,
    urgent: true,
    amount: 5000000,
    target: 12000000,
    daysLeft: 10,
    description: 'Run dengue fever prevention campaigns and distribute abate powder to eliminate mosquito larvae.',
    storyDate: '02 Agt 2024',
    donors: [ { name: 'Yuni A', amount: 25000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga lingkungan kita bebas DBD.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '01 Agt 2024', count: 1 } ],
    withdrawals: [ { date: '31 Jul 2024', count: 1 } ],
    donationCount: 80,
    prayerCount: 6,
  },
  {
    id: 16,
    image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80',
    title: 'Childhood Cancer Support',
    organization: 'Harapan Anak',
    orgLogo: 'https://ui-avatars.com/api/?name=HA&background=4f46e5&color=fff',
    verified: true,
    urgent: true,
    amount: 15000000,
    target: 30000000,
    daysLeft: 25,
    description: 'Support children with cancer and their families with treatment, accommodation, and emotional support.',
    storyDate: '01 Agt 2024',
    donors: [ { name: 'Rina S', amount: 100000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga anak-anak kuat dan sembuh.', time: '3 jam yang lalu', count: 3 } ],
    updates: [ { date: '31 Jul 2024', count: 2 } ],
    withdrawals: [ { date: '30 Jul 2024', count: 1 } ],
    donationCount: 300,
    prayerCount: 20,
  },
  {
    id: 17,
    image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80',
    title: 'Mental Health Hotline for Youth',
    organization: 'Sahabat Remaja',
    orgLogo: 'https://ui-avatars.com/api/?name=SR&background=22c55e&color=fff',
    verified: true,
    urgent: false,
    amount: 2000000,
    target: 10000000,
    daysLeft: 18,
    description: 'Fund a 24/7 mental health hotline for teens in crisis. Every call can save a life.',
    storyDate: '31 Jul 2024',
    donors: [ { name: 'Dewi S', amount: 50000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga remaja Indonesia sehat mental.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '30 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '29 Jul 2024', count: 1 } ],
    donationCount: 60,
    prayerCount: 5,
  },
  {
    id: 18,
    image: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=800&q=80',
    title: 'Clean Hands, Healthy Kids',
    organization: 'Cuci Tangan Indonesia',
    orgLogo: 'https://ui-avatars.com/api/?name=CTI&background=ef4444&color=fff',
    verified: true,
    urgent: false,
    amount: 3000000,
    target: 9000000,
    daysLeft: 12,
    description: 'Promote handwashing and hygiene education in schools to prevent disease.',
    storyDate: '30 Jul 2024',
    donors: [ { name: 'Budi S', amount: 20000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga anak-anak sehat selalu.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '29 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '28 Jul 2024', count: 1 } ],
    donationCount: 40,
    prayerCount: 3,
  },
  {
    id: 19,
    image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80',
    title: 'Safe Water for Pregnant Women',
    organization: 'Air Bersih Ibu',
    orgLogo: 'https://ui-avatars.com/api/?name=ABI&background=0ea5e9&color=fff',
    verified: true,
    urgent: true,
    amount: 8000000,
    target: 20000000,
    daysLeft: 16,
    description: 'Provide clean water access and hygiene kits for pregnant women in remote villages.',
    storyDate: '29 Jul 2024',
    donors: [ { name: 'Linda M', amount: 75000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga ibu dan bayi sehat.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '28 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '27 Jul 2024', count: 1 } ],
    donationCount: 100,
    prayerCount: 8,
  },
  {
    id: 20,
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80',
    title: 'Healthy School Meals',
    organization: 'Makan Sehat Anak',
    orgLogo: 'https://ui-avatars.com/api/?name=MSA&background=4f46e5&color=fff',
    verified: true,
    urgent: false,
    amount: 6000000,
    target: 15000000,
    daysLeft: 14,
    description: 'Fund nutritious school meals for children in low-income areas.',
    storyDate: '28 Jul 2024',
    donors: [ { name: 'Andi W', amount: 30000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga anak-anak tumbuh sehat dan kuat.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '27 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '26 Jul 2024', count: 1 } ],
    donationCount: 80,
    prayerCount: 6,
  },
  {
    id: 21,
    image: 'https://images.unsplash.com/photo-1504439468489-c8920d796a29?auto=format&fit=crop&w=800&q=80',
    title: 'Community Mental Health Workshops',
    organization: 'Mindful Nusantara',
    orgLogo: 'https://ui-avatars.com/api/?name=MN&background=0ea5e9&color=fff',
    verified: true,
    urgent: false,
    amount: 3500000,
    target: 12000000,
    daysLeft: 21,
    description: 'Support mental health awareness and resilience workshops for families and youth in rural communities.',
    storyDate: '27 Jul 2024',
    donors: [ { name: 'Putri S', amount: 25000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua sehat mental.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '26 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '25 Jul 2024', count: 1 } ],
    donationCount: 60,
    prayerCount: 4,
  },
  {
    id: 22,
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    title: 'Childhood Immunization Drive',
    organization: 'Vaksinasi Ceria',
    orgLogo: 'https://ui-avatars.com/api/?name=VC&background=22c55e&color=fff',
    verified: true,
    urgent: true,
    amount: 9000000,
    target: 25000000,
    daysLeft: 18,
    description: 'Fund vaccines and outreach for children in remote areas to prevent deadly diseases.',
    storyDate: '26 Jul 2024',
    donors: [ { name: 'Rina A', amount: 50000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua anak sehat dan imun.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '25 Jul 2024', count: 2 } ],
    withdrawals: [ { date: '24 Jul 2024', count: 1 } ],
    donationCount: 120,
    prayerCount: 10,
  },
  {
    id: 23,
    image: 'https://images.unsplash.com/photo-1465398498260-c97c7b1b7b88?auto=format&fit=crop&w=800&q=80',
    title: 'Hygiene Kits for Flood Victims',
    organization: 'Bersih Bersama',
    orgLogo: 'https://ui-avatars.com/api/?name=BB&background=f59e42&color=fff',
    verified: true,
    urgent: true,
    amount: 12000000,
    target: 30000000,
    daysLeft: 12,
    description: 'Distribute hygiene kits and health education to families affected by floods and disasters.',
    storyDate: '25 Jul 2024',
    donors: [ { name: 'Dewi L', amount: 100000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua selamat dan sehat.', time: '2 jam yang lalu', count: 3 } ],
    updates: [ { date: '24 Jul 2024', count: 2 } ],
    withdrawals: [ { date: '23 Jul 2024', count: 1 } ],
    donationCount: 200,
    prayerCount: 20,
  },
  {
    id: 24,
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=80',
    title: 'Vision Care for the Elderly',
    organization: 'Mata Sehat Lansia',
    orgLogo: 'https://ui-avatars.com/api/?name=MSL&background=ef4444&color=fff',
    verified: true,
    urgent: false,
    amount: 5000000,
    target: 12000000,
    daysLeft: 15,
    description: 'Provide free eye exams and glasses for elderly people in need.',
    storyDate: '24 Jul 2024',
    donors: [ { name: 'Budi T', amount: 40000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga para lansia bisa melihat dengan jelas.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '23 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '22 Jul 2024', count: 1 } ],
    donationCount: 100,
    prayerCount: 8,
  },
  {
    id: 25,
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80',
    title: 'Nutrition for Pregnant Mothers',
    organization: 'Gizi Ibu Nusantara',
    orgLogo: 'https://ui-avatars.com/api/?name=GIN&background=0ea5e9&color=fff',
    verified: true,
    urgent: true,
    amount: 8000000,
    target: 20000000,
    daysLeft: 16,
    description: 'Provide nutrition supplements and counseling for pregnant mothers in rural areas.',
    storyDate: '23 Jul 2024',
    donors: [ { name: 'Linda N', amount: 75000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga ibu dan bayi sehat.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '22 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '21 Jul 2024', count: 1 } ],
    donationCount: 100,
    prayerCount: 8,
  },
  {
    id: 26,
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    title: 'Hepatitis B Vaccination for Newborns',
    organization: 'Vaksin Bayi Sehat',
    orgLogo: 'https://ui-avatars.com/api/?name=VBS&background=4f46e5&color=fff',
    verified: true,
    urgent: true,
    amount: 6000000,
    target: 15000000,
    daysLeft: 14,
    description: 'Fund hepatitis B vaccines for newborns in remote clinics.',
    storyDate: '22 Jul 2024',
    donors: [ { name: 'Andi S', amount: 30000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga bayi-bayi sehat dan imun.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '21 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '20 Jul 2024', count: 1 } ],
    donationCount: 80,
    prayerCount: 6,
  },
  {
    id: 27,
    image: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=800&q=80',
    title: 'Disaster Response Medical Kits',
    organization: 'Tanggap Sehat',
    orgLogo: 'https://ui-avatars.com/api/?name=TS&background=22c55e&color=fff',
    verified: true,
    urgent: true,
    amount: 12000000,
    target: 30000000,
    daysLeft: 12,
    description: 'Distribute emergency medical kits to families affected by natural disasters.',
    storyDate: '21 Jul 2024',
    donors: [ { name: 'Dewi F', amount: 100000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua selamat dan sehat.', time: '2 jam yang lalu', count: 3 } ],
    updates: [ { date: '20 Jul 2024', count: 2 } ],
    withdrawals: [ { date: '19 Jul 2024', count: 1 } ],
    donationCount: 200,
    prayerCount: 20,
  },
  {
    id: 28,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    title: 'School Health Screening',
    organization: 'Sehat di Sekolah',
    orgLogo: 'https://ui-avatars.com/api/?name=SDS&background=f59e42&color=fff',
    verified: true,
    urgent: false,
    amount: 5000000,
    target: 12000000,
    daysLeft: 15,
    description: 'Provide annual health screenings for students to detect and address health issues early.',
    storyDate: '20 Jul 2024',
    donors: [ { name: 'Budi K', amount: 40000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua anak sehat.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '19 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '18 Jul 2024', count: 1 } ],
    donationCount: 100,
    prayerCount: 8,
  },
  {
    id: 29,
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&q=80',
    title: 'Nutrition Education for Teens',
    organization: 'Remaja Sehat',
    orgLogo: 'https://ui-avatars.com/api/?name=RS&background=0ea5e9&color=fff',
    verified: true,
    urgent: false,
    amount: 8000000,
    target: 20000000,
    daysLeft: 16,
    description: 'Run nutrition education workshops for teenagers to promote healthy eating habits.',
    storyDate: '19 Jul 2024',
    donors: [ { name: 'Linda P', amount: 75000, time: '2 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga remaja sehat dan kuat.', time: '3 jam yang lalu', count: 2 } ],
    updates: [ { date: '18 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '17 Jul 2024', count: 1 } ],
    donationCount: 100,
    prayerCount: 8,
  },
  {
    id: 30,
    image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80',
    title: 'Mobile Health Education Van',
    organization: 'Edukasi Sehat Bergerak',
    orgLogo: 'https://ui-avatars.com/api/?name=ESB&background=4f46e5&color=fff',
    verified: true,
    urgent: false,
    amount: 6000000,
    target: 15000000,
    daysLeft: 14,
    description: 'Bring health education and resources to remote communities with our mobile van.',
    storyDate: '18 Jul 2024',
    donors: [ { name: 'Andi Q', amount: 30000, time: '1 jam yang lalu' } ],
    prayers: [ { name: 'Orang Baik', text: 'Semoga semua masyarakat sehat.', time: '2 jam yang lalu', count: 1 } ],
    updates: [ { date: '17 Jul 2024', count: 1 } ],
    withdrawals: [ { date: '16 Jul 2024', count: 1 } ],
    donationCount: 80,
    prayerCount: 6,
  },
];

export type Campaign = typeof samplePrograms[number]; 